# Generated by Django 4.2.6 on 2023-10-08 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_article_image_articleseries_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='notes',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=main.models.Article.image_upload_to, verbose_name="Rasm qo'yish shart"),
        ),
        migrations.AlterField(
            model_name='article',
            name='series',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.articleseries', verbose_name="Qaysi bo'limga tegishli"),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Mavzu haqida qisqacha ma'lumot"),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Mavzu sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=main.models.ArticleSeries.image_upload_to, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='articleseries',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='articleseries',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Qo'shimcha sarlavha"),
        ),
        migrations.AlterField(
            model_name='articleseries',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
    ]
